[DIA-3236] Add 2 more checks in the getMessagesUrl test
SourcePointUSA/android-cmp-app pull request #768
Opened 2023-12-07 12:06 UTC by bohdan-go-wombat

2023-12-08 11:52 UTC, Nevazhnovu approved these changes

2023-12-08 13:37 UTC, carmelo-iriti requested changes

2023-12-08 13:37 UTC, carmelo-iriti commented on cmplibrary/src/test/java/com/sourcepoint/cmplibrary/data/network/util/HttpUrlManagerTest.kt
> +        val fakeNonKeyedLocalState = buildJsonObject {
too complex, we can remove it

2023-12-08 13:37 UTC, carmelo-iriti commented on cmplibrary/src/test/java/com/sourcepoint/cmplibrary/data/network/util/HttpUrlManagerTest.kt
> +            nonKeyedLocalState = fakeNonKeyedLocalState,
just use something like this  JsonObject(mapOf("a" to "a")) and check the condition

2023-12-08 13:37 UTC, carmelo-iriti commented on cmplibrary/src/test/java/com/sourcepoint/cmplibrary/data/network/util/HttpUrlManagerTest.kt
> +            nonKeyedLocalState = fakeNonKeyedLocalState,
the same for localState

2023-12-11 10:14 UTC, carmelo-iriti approved these changes

2023-12-11 10:43 UTC, merged